// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CBOS.Data.Entities;

public partial class Discorduser
{
    public string Id { get; set; }

    public string Name { get; set; }

    public DateTime Createddate { get; set; }

    public DateTime Modifieddate { get; set; }

    public virtual ICollection<Guild> Guilds { get; set; } = new List<Guild>();
}