// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CBOS.Data.Entities;

public partial class Guild
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Ownerid { get; set; }

    public DateTime Createddate { get; set; }

    public DateTime Modifieddate { get; set; }

    public virtual Discorduser Owner { get; set; }
}